/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RentRouteImport } from './routes/rent'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CardRouteImport } from './routes/card'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimesheetsRouteImport } from './routes/_authenticated/timesheets'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSubscriptionPlansRouteImport } from './routes/_authenticated/subscription-plans'
import { Route as AuthenticatedSubmittalsRouteImport } from './routes/_authenticated/submittals'
import { Route as AuthenticatedSubcontractsRouteImport } from './routes/_authenticated/subcontracts'
import { Route as AuthenticatedSopFormsRouteImport } from './routes/_authenticated/sop-forms'
import { Route as AuthenticatedSopChecklistsRouteImport } from './routes/_authenticated/sop-checklists'
import { Route as AuthenticatedSopRouteImport } from './routes/_authenticated/sop'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSafetyIncidentsRouteImport } from './routes/_authenticated/safety-incidents'
import { Route as AuthenticatedRfisRouteImport } from './routes/_authenticated/rfis'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRentalTaxDashboardRouteImport } from './routes/_authenticated/rental-tax-dashboard'
import { Route as AuthenticatedRentalMessagesRouteImport } from './routes/_authenticated/rental-messages'
import { Route as AuthenticatedRentalIdCardsRouteImport } from './routes/_authenticated/rental-id-cards'
import { Route as AuthenticatedRecurringBillingRouteImport } from './routes/_authenticated/recurring-billing'
import { Route as AuthenticatedReceiptsRouteImport } from './routes/_authenticated/receipts'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPunchListRouteImport } from './routes/_authenticated/punch-list'
import { Route as AuthenticatedProposalsRouteImport } from './routes/_authenticated/proposals'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProjectTasksRouteImport } from './routes/_authenticated/project-tasks'
import { Route as AuthenticatedProjectSchedulesRouteImport } from './routes/_authenticated/project-schedules'
import { Route as AuthenticatedProjectPhotosRouteImport } from './routes/_authenticated/project-photos'
import { Route as AuthenticatedProjectDocumentsRouteImport } from './routes/_authenticated/project-documents'
import { Route as AuthenticatedProjectDashboardRouteImport } from './routes/_authenticated/project-dashboard'
import { Route as AuthenticatedProjectBudgetRouteImport } from './routes/_authenticated/project-budget'
import { Route as AuthenticatedProgressPaymentsRouteImport } from './routes/_authenticated/progress-payments'
import { Route as AuthenticatedPreventativeMaintenanceRouteImport } from './routes/_authenticated/preventative-maintenance'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPaymentProofsRouteImport } from './routes/_authenticated/payment-proofs'
import { Route as AuthenticatedMyIdCardRouteImport } from './routes/_authenticated/my-id-card'
import { Route as AuthenticatedMeetingMinutesRouteImport } from './routes/_authenticated/meeting-minutes'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedListingBannersRouteImport } from './routes/_authenticated/listing-banners'
import { Route as AuthenticatedLienWaiversRouteImport } from './routes/_authenticated/lien-waivers'
import { Route as AuthenticatedLeasesRouteImport } from './routes/_authenticated/leases'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLandlordsRouteImport } from './routes/_authenticated/landlords'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinancialReportsRouteImport } from './routes/_authenticated/financial-reports'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedEstimatesRouteImport } from './routes/_authenticated/estimates'
import { Route as AuthenticatedEquipmentRentalsRouteImport } from './routes/_authenticated/equipment-rentals'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedELeasingRouteImport } from './routes/_authenticated/e-leasing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyLogsRouteImport } from './routes/_authenticated/daily-logs'
import { Route as AuthenticatedCostCodesRouteImport } from './routes/_authenticated/cost-codes'
import { Route as AuthenticatedConstructionInvoicesRouteImport } from './routes/_authenticated/construction-invoices'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedCommitmentLogRouteImport } from './routes/_authenticated/commitment-log'
import { Route as AuthenticatedChangeOrdersRouteImport } from './routes/_authenticated/change-orders'
import { Route as AuthenticatedBillsRouteImport } from './routes/_authenticated/bills'
import { Route as AuthenticatedBidPackagesRouteImport } from './routes/_authenticated/bid-packages'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAllowancesRouteImport } from './routes/_authenticated/allowances'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated/properties.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CardRoute = CardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimesheetsRoute = AuthenticatedTimesheetsRouteImport.update({
  id: '/timesheets',
  path: '/timesheets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubscriptionPlansRoute =
  AuthenticatedSubscriptionPlansRouteImport.update({
    id: '/subscription-plans',
    path: '/subscription-plans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubmittalsRoute = AuthenticatedSubmittalsRouteImport.update({
  id: '/submittals',
  path: '/submittals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSubcontractsRoute =
  AuthenticatedSubcontractsRouteImport.update({
    id: '/subcontracts',
    path: '/subcontracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopFormsRoute = AuthenticatedSopFormsRouteImport.update({
  id: '/sop-forms',
  path: '/sop-forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSopChecklistsRoute =
  AuthenticatedSopChecklistsRouteImport.update({
    id: '/sop-checklists',
    path: '/sop-checklists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopRoute = AuthenticatedSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSafetyIncidentsRoute =
  AuthenticatedSafetyIncidentsRouteImport.update({
    id: '/safety-incidents',
    path: '/safety-incidents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRfisRoute = AuthenticatedRfisRouteImport.update({
  id: '/rfis',
  path: '/rfis',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRentalTaxDashboardRoute =
  AuthenticatedRentalTaxDashboardRouteImport.update({
    id: '/rental-tax-dashboard',
    path: '/rental-tax-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRentalMessagesRoute =
  AuthenticatedRentalMessagesRouteImport.update({
    id: '/rental-messages',
    path: '/rental-messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRentalIdCardsRoute =
  AuthenticatedRentalIdCardsRouteImport.update({
    id: '/rental-id-cards',
    path: '/rental-id-cards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecurringBillingRoute =
  AuthenticatedRecurringBillingRouteImport.update({
    id: '/recurring-billing',
    path: '/recurring-billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceiptsRoute = AuthenticatedReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPunchListRoute = AuthenticatedPunchListRouteImport.update({
  id: '/punch-list',
  path: '/punch-list',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProposalsRoute = AuthenticatedProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectTasksRoute =
  AuthenticatedProjectTasksRouteImport.update({
    id: '/project-tasks',
    path: '/project-tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectSchedulesRoute =
  AuthenticatedProjectSchedulesRouteImport.update({
    id: '/project-schedules',
    path: '/project-schedules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectPhotosRoute =
  AuthenticatedProjectPhotosRouteImport.update({
    id: '/project-photos',
    path: '/project-photos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectDocumentsRoute =
  AuthenticatedProjectDocumentsRouteImport.update({
    id: '/project-documents',
    path: '/project-documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectDashboardRoute =
  AuthenticatedProjectDashboardRouteImport.update({
    id: '/project-dashboard',
    path: '/project-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectBudgetRoute =
  AuthenticatedProjectBudgetRouteImport.update({
    id: '/project-budget',
    path: '/project-budget',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProgressPaymentsRoute =
  AuthenticatedProgressPaymentsRouteImport.update({
    id: '/progress-payments',
    path: '/progress-payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPreventativeMaintenanceRoute =
  AuthenticatedPreventativeMaintenanceRouteImport.update({
    id: '/preventative-maintenance',
    path: '/preventative-maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentProofsRoute =
  AuthenticatedPaymentProofsRouteImport.update({
    id: '/payment-proofs',
    path: '/payment-proofs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyIdCardRoute = AuthenticatedMyIdCardRouteImport.update({
  id: '/my-id-card',
  path: '/my-id-card',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeetingMinutesRoute =
  AuthenticatedMeetingMinutesRouteImport.update({
    id: '/meeting-minutes',
    path: '/meeting-minutes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListingBannersRoute =
  AuthenticatedListingBannersRouteImport.update({
    id: '/listing-banners',
    path: '/listing-banners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLienWaiversRoute =
  AuthenticatedLienWaiversRouteImport.update({
    id: '/lien-waivers',
    path: '/lien-waivers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeasesRoute = AuthenticatedLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLandlordsRoute = AuthenticatedLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialReportsRoute =
  AuthenticatedFinancialReportsRouteImport.update({
    id: '/financial-reports',
    path: '/financial-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEstimatesRoute = AuthenticatedEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRentalsRoute =
  AuthenticatedEquipmentRentalsRouteImport.update({
    id: '/equipment-rentals',
    path: '/equipment-rentals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedELeasingRoute = AuthenticatedELeasingRouteImport.update({
  id: '/e-leasing',
  path: '/e-leasing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDailyLogsRoute = AuthenticatedDailyLogsRouteImport.update({
  id: '/daily-logs',
  path: '/daily-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCostCodesRoute = AuthenticatedCostCodesRouteImport.update({
  id: '/cost-codes',
  path: '/cost-codes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConstructionInvoicesRoute =
  AuthenticatedConstructionInvoicesRouteImport.update({
    id: '/construction-invoices',
    path: '/construction-invoices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommitmentLogRoute =
  AuthenticatedCommitmentLogRouteImport.update({
    id: '/commitment-log',
    path: '/commitment-log',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChangeOrdersRoute =
  AuthenticatedChangeOrdersRouteImport.update({
    id: '/change-orders',
    path: '/change-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillsRoute = AuthenticatedBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBidPackagesRoute =
  AuthenticatedBidPackagesRouteImport.update({
    id: '/bid-packages',
    path: '/bid-packages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAllowancesRoute = AuthenticatedAllowancesRouteImport.update({
  id: '/allowances',
  path: '/allowances',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/allowances': typeof AuthenticatedAllowancesRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/bid-packages': typeof AuthenticatedBidPackagesRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/change-orders': typeof AuthenticatedChangeOrdersRoute
  '/commitment-log': typeof AuthenticatedCommitmentLogRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/construction-invoices': typeof AuthenticatedConstructionInvoicesRoute
  '/cost-codes': typeof AuthenticatedCostCodesRoute
  '/daily-logs': typeof AuthenticatedDailyLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/e-leasing': typeof AuthenticatedELeasingRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/landlords': typeof AuthenticatedLandlordsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/lien-waivers': typeof AuthenticatedLienWaiversRoute
  '/listing-banners': typeof AuthenticatedListingBannersRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/meeting-minutes': typeof AuthenticatedMeetingMinutesRoute
  '/my-id-card': typeof AuthenticatedMyIdCardRoute
  '/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/progress-payments': typeof AuthenticatedProgressPaymentsRoute
  '/project-budget': typeof AuthenticatedProjectBudgetRoute
  '/project-dashboard': typeof AuthenticatedProjectDashboardRoute
  '/project-documents': typeof AuthenticatedProjectDocumentsRoute
  '/project-photos': typeof AuthenticatedProjectPhotosRoute
  '/project-schedules': typeof AuthenticatedProjectSchedulesRoute
  '/project-tasks': typeof AuthenticatedProjectTasksRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/proposals': typeof AuthenticatedProposalsRoute
  '/punch-list': typeof AuthenticatedPunchListRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfis': typeof AuthenticatedRfisRoute
  '/safety-incidents': typeof AuthenticatedSafetyIncidentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sop': typeof AuthenticatedSopRoute
  '/sop-checklists': typeof AuthenticatedSopChecklistsRoute
  '/sop-forms': typeof AuthenticatedSopFormsRoute
  '/subcontracts': typeof AuthenticatedSubcontractsRoute
  '/submittals': typeof AuthenticatedSubmittalsRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/allowances': typeof AuthenticatedAllowancesRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/bid-packages': typeof AuthenticatedBidPackagesRoute
  '/bills': typeof AuthenticatedBillsRoute
  '/change-orders': typeof AuthenticatedChangeOrdersRoute
  '/commitment-log': typeof AuthenticatedCommitmentLogRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/construction-invoices': typeof AuthenticatedConstructionInvoicesRoute
  '/cost-codes': typeof AuthenticatedCostCodesRoute
  '/daily-logs': typeof AuthenticatedDailyLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/e-leasing': typeof AuthenticatedELeasingRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/estimates': typeof AuthenticatedEstimatesRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/landlords': typeof AuthenticatedLandlordsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/lien-waivers': typeof AuthenticatedLienWaiversRoute
  '/listing-banners': typeof AuthenticatedListingBannersRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/meeting-minutes': typeof AuthenticatedMeetingMinutesRoute
  '/my-id-card': typeof AuthenticatedMyIdCardRoute
  '/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/progress-payments': typeof AuthenticatedProgressPaymentsRoute
  '/project-budget': typeof AuthenticatedProjectBudgetRoute
  '/project-dashboard': typeof AuthenticatedProjectDashboardRoute
  '/project-documents': typeof AuthenticatedProjectDocumentsRoute
  '/project-photos': typeof AuthenticatedProjectPhotosRoute
  '/project-schedules': typeof AuthenticatedProjectSchedulesRoute
  '/project-tasks': typeof AuthenticatedProjectTasksRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/proposals': typeof AuthenticatedProposalsRoute
  '/punch-list': typeof AuthenticatedPunchListRoute
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/receipts': typeof AuthenticatedReceiptsRoute
  '/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/rfis': typeof AuthenticatedRfisRoute
  '/safety-incidents': typeof AuthenticatedSafetyIncidentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sop': typeof AuthenticatedSopRoute
  '/sop-checklists': typeof AuthenticatedSopChecklistsRoute
  '/sop-forms': typeof AuthenticatedSopFormsRoute
  '/subcontracts': typeof AuthenticatedSubcontractsRoute
  '/submittals': typeof AuthenticatedSubmittalsRoute
  '/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/timesheets': typeof AuthenticatedTimesheetsRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/card': typeof CardRoute
  '/contact': typeof ContactRoute
  '/register': typeof RegisterRoute
  '/rent': typeof RentRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/allowances': typeof AuthenticatedAllowancesRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/bid-packages': typeof AuthenticatedBidPackagesRoute
  '/_authenticated/bills': typeof AuthenticatedBillsRoute
  '/_authenticated/change-orders': typeof AuthenticatedChangeOrdersRoute
  '/_authenticated/commitment-log': typeof AuthenticatedCommitmentLogRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/construction-invoices': typeof AuthenticatedConstructionInvoicesRoute
  '/_authenticated/cost-codes': typeof AuthenticatedCostCodesRoute
  '/_authenticated/daily-logs': typeof AuthenticatedDailyLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/e-leasing': typeof AuthenticatedELeasingRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/_authenticated/estimates': typeof AuthenticatedEstimatesRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/landlords': typeof AuthenticatedLandlordsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/leases': typeof AuthenticatedLeasesRoute
  '/_authenticated/lien-waivers': typeof AuthenticatedLienWaiversRoute
  '/_authenticated/listing-banners': typeof AuthenticatedListingBannersRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/meeting-minutes': typeof AuthenticatedMeetingMinutesRoute
  '/_authenticated/my-id-card': typeof AuthenticatedMyIdCardRoute
  '/_authenticated/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/_authenticated/progress-payments': typeof AuthenticatedProgressPaymentsRoute
  '/_authenticated/project-budget': typeof AuthenticatedProjectBudgetRoute
  '/_authenticated/project-dashboard': typeof AuthenticatedProjectDashboardRoute
  '/_authenticated/project-documents': typeof AuthenticatedProjectDocumentsRoute
  '/_authenticated/project-photos': typeof AuthenticatedProjectPhotosRoute
  '/_authenticated/project-schedules': typeof AuthenticatedProjectSchedulesRoute
  '/_authenticated/project-tasks': typeof AuthenticatedProjectTasksRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/_authenticated/proposals': typeof AuthenticatedProposalsRoute
  '/_authenticated/punch-list': typeof AuthenticatedPunchListRoute
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/receipts': typeof AuthenticatedReceiptsRoute
  '/_authenticated/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/_authenticated/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/_authenticated/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/_authenticated/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/rfis': typeof AuthenticatedRfisRoute
  '/_authenticated/safety-incidents': typeof AuthenticatedSafetyIncidentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sop': typeof AuthenticatedSopRoute
  '/_authenticated/sop-checklists': typeof AuthenticatedSopChecklistsRoute
  '/_authenticated/sop-forms': typeof AuthenticatedSopFormsRoute
  '/_authenticated/subcontracts': typeof AuthenticatedSubcontractsRoute
  '/_authenticated/submittals': typeof AuthenticatedSubmittalsRoute
  '/_authenticated/subscription-plans': typeof AuthenticatedSubscriptionPlansRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/timesheets': typeof AuthenticatedTimesheetsRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/card'
    | '/contact'
    | '/register'
    | '/rent'
    | '/services'
    | '/sitemap.xml'
    | '/allowances'
    | '/assets'
    | '/bid-packages'
    | '/bills'
    | '/change-orders'
    | '/commitment-log'
    | '/companies'
    | '/construction-invoices'
    | '/cost-codes'
    | '/daily-logs'
    | '/dashboard'
    | '/e-leasing'
    | '/employees'
    | '/equipment-rentals'
    | '/estimates'
    | '/expenses'
    | '/financial-reports'
    | '/inventory'
    | '/landlords'
    | '/leads'
    | '/leases'
    | '/lien-waivers'
    | '/listing-banners'
    | '/maintenance'
    | '/meeting-minutes'
    | '/my-id-card'
    | '/payment-proofs'
    | '/payments'
    | '/preventative-maintenance'
    | '/progress-payments'
    | '/project-budget'
    | '/project-dashboard'
    | '/project-documents'
    | '/project-photos'
    | '/project-schedules'
    | '/project-tasks'
    | '/projects'
    | '/properties'
    | '/proposals'
    | '/punch-list'
    | '/purchase-orders'
    | '/receipts'
    | '/recurring-billing'
    | '/rental-id-cards'
    | '/rental-messages'
    | '/rental-tax-dashboard'
    | '/reports'
    | '/rfis'
    | '/safety-incidents'
    | '/settings'
    | '/sop'
    | '/sop-checklists'
    | '/sop-forms'
    | '/subcontracts'
    | '/submittals'
    | '/subscription-plans'
    | '/suppliers'
    | '/tenants'
    | '/timesheets'
    | '/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/card'
    | '/contact'
    | '/register'
    | '/rent'
    | '/services'
    | '/sitemap.xml'
    | '/allowances'
    | '/assets'
    | '/bid-packages'
    | '/bills'
    | '/change-orders'
    | '/commitment-log'
    | '/companies'
    | '/construction-invoices'
    | '/cost-codes'
    | '/daily-logs'
    | '/dashboard'
    | '/e-leasing'
    | '/employees'
    | '/equipment-rentals'
    | '/estimates'
    | '/expenses'
    | '/financial-reports'
    | '/inventory'
    | '/landlords'
    | '/leads'
    | '/leases'
    | '/lien-waivers'
    | '/listing-banners'
    | '/maintenance'
    | '/meeting-minutes'
    | '/my-id-card'
    | '/payment-proofs'
    | '/payments'
    | '/preventative-maintenance'
    | '/progress-payments'
    | '/project-budget'
    | '/project-dashboard'
    | '/project-documents'
    | '/project-photos'
    | '/project-schedules'
    | '/project-tasks'
    | '/projects'
    | '/properties'
    | '/proposals'
    | '/punch-list'
    | '/purchase-orders'
    | '/receipts'
    | '/recurring-billing'
    | '/rental-id-cards'
    | '/rental-messages'
    | '/rental-tax-dashboard'
    | '/reports'
    | '/rfis'
    | '/safety-incidents'
    | '/settings'
    | '/sop'
    | '/sop-checklists'
    | '/sop-forms'
    | '/subcontracts'
    | '/submittals'
    | '/subscription-plans'
    | '/suppliers'
    | '/tenants'
    | '/timesheets'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/card'
    | '/contact'
    | '/register'
    | '/rent'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/allowances'
    | '/_authenticated/assets'
    | '/_authenticated/bid-packages'
    | '/_authenticated/bills'
    | '/_authenticated/change-orders'
    | '/_authenticated/commitment-log'
    | '/_authenticated/companies'
    | '/_authenticated/construction-invoices'
    | '/_authenticated/cost-codes'
    | '/_authenticated/daily-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/e-leasing'
    | '/_authenticated/employees'
    | '/_authenticated/equipment-rentals'
    | '/_authenticated/estimates'
    | '/_authenticated/expenses'
    | '/_authenticated/financial-reports'
    | '/_authenticated/inventory'
    | '/_authenticated/landlords'
    | '/_authenticated/leads'
    | '/_authenticated/leases'
    | '/_authenticated/lien-waivers'
    | '/_authenticated/listing-banners'
    | '/_authenticated/maintenance'
    | '/_authenticated/meeting-minutes'
    | '/_authenticated/my-id-card'
    | '/_authenticated/payment-proofs'
    | '/_authenticated/payments'
    | '/_authenticated/preventative-maintenance'
    | '/_authenticated/progress-payments'
    | '/_authenticated/project-budget'
    | '/_authenticated/project-dashboard'
    | '/_authenticated/project-documents'
    | '/_authenticated/project-photos'
    | '/_authenticated/project-schedules'
    | '/_authenticated/project-tasks'
    | '/_authenticated/projects'
    | '/_authenticated/properties'
    | '/_authenticated/proposals'
    | '/_authenticated/punch-list'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/receipts'
    | '/_authenticated/recurring-billing'
    | '/_authenticated/rental-id-cards'
    | '/_authenticated/rental-messages'
    | '/_authenticated/rental-tax-dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/rfis'
    | '/_authenticated/safety-incidents'
    | '/_authenticated/settings'
    | '/_authenticated/sop'
    | '/_authenticated/sop-checklists'
    | '/_authenticated/sop-forms'
    | '/_authenticated/subcontracts'
    | '/_authenticated/submittals'
    | '/_authenticated/subscription-plans'
    | '/_authenticated/suppliers'
    | '/_authenticated/tenants'
    | '/_authenticated/timesheets'
    | '/_authenticated/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CardRoute: typeof CardRoute
  ContactRoute: typeof ContactRoute
  RegisterRoute: typeof RegisterRoute
  RentRoute: typeof RentRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card': {
      id: '/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof CardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/timesheets': {
      id: '/_authenticated/timesheets'
      path: '/timesheets'
      fullPath: '/timesheets'
      preLoaderRoute: typeof AuthenticatedTimesheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription-plans': {
      id: '/_authenticated/subscription-plans'
      path: '/subscription-plans'
      fullPath: '/subscription-plans'
      preLoaderRoute: typeof AuthenticatedSubscriptionPlansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/submittals': {
      id: '/_authenticated/submittals'
      path: '/submittals'
      fullPath: '/submittals'
      preLoaderRoute: typeof AuthenticatedSubmittalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subcontracts': {
      id: '/_authenticated/subcontracts'
      path: '/subcontracts'
      fullPath: '/subcontracts'
      preLoaderRoute: typeof AuthenticatedSubcontractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop-forms': {
      id: '/_authenticated/sop-forms'
      path: '/sop-forms'
      fullPath: '/sop-forms'
      preLoaderRoute: typeof AuthenticatedSopFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop-checklists': {
      id: '/_authenticated/sop-checklists'
      path: '/sop-checklists'
      fullPath: '/sop-checklists'
      preLoaderRoute: typeof AuthenticatedSopChecklistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop': {
      id: '/_authenticated/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof AuthenticatedSopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/safety-incidents': {
      id: '/_authenticated/safety-incidents'
      path: '/safety-incidents'
      fullPath: '/safety-incidents'
      preLoaderRoute: typeof AuthenticatedSafetyIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfis': {
      id: '/_authenticated/rfis'
      path: '/rfis'
      fullPath: '/rfis'
      preLoaderRoute: typeof AuthenticatedRfisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-tax-dashboard': {
      id: '/_authenticated/rental-tax-dashboard'
      path: '/rental-tax-dashboard'
      fullPath: '/rental-tax-dashboard'
      preLoaderRoute: typeof AuthenticatedRentalTaxDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-messages': {
      id: '/_authenticated/rental-messages'
      path: '/rental-messages'
      fullPath: '/rental-messages'
      preLoaderRoute: typeof AuthenticatedRentalMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-id-cards': {
      id: '/_authenticated/rental-id-cards'
      path: '/rental-id-cards'
      fullPath: '/rental-id-cards'
      preLoaderRoute: typeof AuthenticatedRentalIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring-billing': {
      id: '/_authenticated/recurring-billing'
      path: '/recurring-billing'
      fullPath: '/recurring-billing'
      preLoaderRoute: typeof AuthenticatedRecurringBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receipts': {
      id: '/_authenticated/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AuthenticatedReceiptsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/punch-list': {
      id: '/_authenticated/punch-list'
      path: '/punch-list'
      fullPath: '/punch-list'
      preLoaderRoute: typeof AuthenticatedPunchListRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/proposals': {
      id: '/_authenticated/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof AuthenticatedProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-tasks': {
      id: '/_authenticated/project-tasks'
      path: '/project-tasks'
      fullPath: '/project-tasks'
      preLoaderRoute: typeof AuthenticatedProjectTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-schedules': {
      id: '/_authenticated/project-schedules'
      path: '/project-schedules'
      fullPath: '/project-schedules'
      preLoaderRoute: typeof AuthenticatedProjectSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-photos': {
      id: '/_authenticated/project-photos'
      path: '/project-photos'
      fullPath: '/project-photos'
      preLoaderRoute: typeof AuthenticatedProjectPhotosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-documents': {
      id: '/_authenticated/project-documents'
      path: '/project-documents'
      fullPath: '/project-documents'
      preLoaderRoute: typeof AuthenticatedProjectDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-dashboard': {
      id: '/_authenticated/project-dashboard'
      path: '/project-dashboard'
      fullPath: '/project-dashboard'
      preLoaderRoute: typeof AuthenticatedProjectDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/project-budget': {
      id: '/_authenticated/project-budget'
      path: '/project-budget'
      fullPath: '/project-budget'
      preLoaderRoute: typeof AuthenticatedProjectBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/progress-payments': {
      id: '/_authenticated/progress-payments'
      path: '/progress-payments'
      fullPath: '/progress-payments'
      preLoaderRoute: typeof AuthenticatedProgressPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventative-maintenance': {
      id: '/_authenticated/preventative-maintenance'
      path: '/preventative-maintenance'
      fullPath: '/preventative-maintenance'
      preLoaderRoute: typeof AuthenticatedPreventativeMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-proofs': {
      id: '/_authenticated/payment-proofs'
      path: '/payment-proofs'
      fullPath: '/payment-proofs'
      preLoaderRoute: typeof AuthenticatedPaymentProofsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-id-card': {
      id: '/_authenticated/my-id-card'
      path: '/my-id-card'
      fullPath: '/my-id-card'
      preLoaderRoute: typeof AuthenticatedMyIdCardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meeting-minutes': {
      id: '/_authenticated/meeting-minutes'
      path: '/meeting-minutes'
      fullPath: '/meeting-minutes'
      preLoaderRoute: typeof AuthenticatedMeetingMinutesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listing-banners': {
      id: '/_authenticated/listing-banners'
      path: '/listing-banners'
      fullPath: '/listing-banners'
      preLoaderRoute: typeof AuthenticatedListingBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lien-waivers': {
      id: '/_authenticated/lien-waivers'
      path: '/lien-waivers'
      fullPath: '/lien-waivers'
      preLoaderRoute: typeof AuthenticatedLienWaiversRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leases': {
      id: '/_authenticated/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AuthenticatedLeasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/landlords': {
      id: '/_authenticated/landlords'
      path: '/landlords'
      fullPath: '/landlords'
      preLoaderRoute: typeof AuthenticatedLandlordsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-reports': {
      id: '/_authenticated/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof AuthenticatedFinancialReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/estimates': {
      id: '/_authenticated/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AuthenticatedEstimatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment-rentals': {
      id: '/_authenticated/equipment-rentals'
      path: '/equipment-rentals'
      fullPath: '/equipment-rentals'
      preLoaderRoute: typeof AuthenticatedEquipmentRentalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/e-leasing': {
      id: '/_authenticated/e-leasing'
      path: '/e-leasing'
      fullPath: '/e-leasing'
      preLoaderRoute: typeof AuthenticatedELeasingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/daily-logs': {
      id: '/_authenticated/daily-logs'
      path: '/daily-logs'
      fullPath: '/daily-logs'
      preLoaderRoute: typeof AuthenticatedDailyLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cost-codes': {
      id: '/_authenticated/cost-codes'
      path: '/cost-codes'
      fullPath: '/cost-codes'
      preLoaderRoute: typeof AuthenticatedCostCodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/construction-invoices': {
      id: '/_authenticated/construction-invoices'
      path: '/construction-invoices'
      fullPath: '/construction-invoices'
      preLoaderRoute: typeof AuthenticatedConstructionInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/commitment-log': {
      id: '/_authenticated/commitment-log'
      path: '/commitment-log'
      fullPath: '/commitment-log'
      preLoaderRoute: typeof AuthenticatedCommitmentLogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-orders': {
      id: '/_authenticated/change-orders'
      path: '/change-orders'
      fullPath: '/change-orders'
      preLoaderRoute: typeof AuthenticatedChangeOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bills': {
      id: '/_authenticated/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AuthenticatedBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bid-packages': {
      id: '/_authenticated/bid-packages'
      path: '/bid-packages'
      fullPath: '/bid-packages'
      preLoaderRoute: typeof AuthenticatedBidPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/allowances': {
      id: '/_authenticated/allowances'
      path: '/allowances'
      fullPath: '/allowances'
      preLoaderRoute: typeof AuthenticatedAllowancesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
  }
}

interface AuthenticatedPropertiesRouteChildren {
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRoute
}

const AuthenticatedPropertiesRouteChildren: AuthenticatedPropertiesRouteChildren =
  {
    AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRoute,
  }

const AuthenticatedPropertiesRouteWithChildren =
  AuthenticatedPropertiesRoute._addFileChildren(
    AuthenticatedPropertiesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAllowancesRoute: typeof AuthenticatedAllowancesRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedBidPackagesRoute: typeof AuthenticatedBidPackagesRoute
  AuthenticatedBillsRoute: typeof AuthenticatedBillsRoute
  AuthenticatedChangeOrdersRoute: typeof AuthenticatedChangeOrdersRoute
  AuthenticatedCommitmentLogRoute: typeof AuthenticatedCommitmentLogRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedConstructionInvoicesRoute: typeof AuthenticatedConstructionInvoicesRoute
  AuthenticatedCostCodesRoute: typeof AuthenticatedCostCodesRoute
  AuthenticatedDailyLogsRoute: typeof AuthenticatedDailyLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedELeasingRoute: typeof AuthenticatedELeasingRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedEquipmentRentalsRoute: typeof AuthenticatedEquipmentRentalsRoute
  AuthenticatedEstimatesRoute: typeof AuthenticatedEstimatesRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinancialReportsRoute: typeof AuthenticatedFinancialReportsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLandlordsRoute: typeof AuthenticatedLandlordsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLeasesRoute: typeof AuthenticatedLeasesRoute
  AuthenticatedLienWaiversRoute: typeof AuthenticatedLienWaiversRoute
  AuthenticatedListingBannersRoute: typeof AuthenticatedListingBannersRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedMeetingMinutesRoute: typeof AuthenticatedMeetingMinutesRoute
  AuthenticatedMyIdCardRoute: typeof AuthenticatedMyIdCardRoute
  AuthenticatedPaymentProofsRoute: typeof AuthenticatedPaymentProofsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPreventativeMaintenanceRoute: typeof AuthenticatedPreventativeMaintenanceRoute
  AuthenticatedProgressPaymentsRoute: typeof AuthenticatedProgressPaymentsRoute
  AuthenticatedProjectBudgetRoute: typeof AuthenticatedProjectBudgetRoute
  AuthenticatedProjectDashboardRoute: typeof AuthenticatedProjectDashboardRoute
  AuthenticatedProjectDocumentsRoute: typeof AuthenticatedProjectDocumentsRoute
  AuthenticatedProjectPhotosRoute: typeof AuthenticatedProjectPhotosRoute
  AuthenticatedProjectSchedulesRoute: typeof AuthenticatedProjectSchedulesRoute
  AuthenticatedProjectTasksRoute: typeof AuthenticatedProjectTasksRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRouteWithChildren
  AuthenticatedProposalsRoute: typeof AuthenticatedProposalsRoute
  AuthenticatedPunchListRoute: typeof AuthenticatedPunchListRoute
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedReceiptsRoute: typeof AuthenticatedReceiptsRoute
  AuthenticatedRecurringBillingRoute: typeof AuthenticatedRecurringBillingRoute
  AuthenticatedRentalIdCardsRoute: typeof AuthenticatedRentalIdCardsRoute
  AuthenticatedRentalMessagesRoute: typeof AuthenticatedRentalMessagesRoute
  AuthenticatedRentalTaxDashboardRoute: typeof AuthenticatedRentalTaxDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedRfisRoute: typeof AuthenticatedRfisRoute
  AuthenticatedSafetyIncidentsRoute: typeof AuthenticatedSafetyIncidentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSopRoute: typeof AuthenticatedSopRoute
  AuthenticatedSopChecklistsRoute: typeof AuthenticatedSopChecklistsRoute
  AuthenticatedSopFormsRoute: typeof AuthenticatedSopFormsRoute
  AuthenticatedSubcontractsRoute: typeof AuthenticatedSubcontractsRoute
  AuthenticatedSubmittalsRoute: typeof AuthenticatedSubmittalsRoute
  AuthenticatedSubscriptionPlansRoute: typeof AuthenticatedSubscriptionPlansRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
  AuthenticatedTimesheetsRoute: typeof AuthenticatedTimesheetsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAllowancesRoute: AuthenticatedAllowancesRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedBidPackagesRoute: AuthenticatedBidPackagesRoute,
  AuthenticatedBillsRoute: AuthenticatedBillsRoute,
  AuthenticatedChangeOrdersRoute: AuthenticatedChangeOrdersRoute,
  AuthenticatedCommitmentLogRoute: AuthenticatedCommitmentLogRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedConstructionInvoicesRoute:
    AuthenticatedConstructionInvoicesRoute,
  AuthenticatedCostCodesRoute: AuthenticatedCostCodesRoute,
  AuthenticatedDailyLogsRoute: AuthenticatedDailyLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedELeasingRoute: AuthenticatedELeasingRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedEquipmentRentalsRoute: AuthenticatedEquipmentRentalsRoute,
  AuthenticatedEstimatesRoute: AuthenticatedEstimatesRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinancialReportsRoute: AuthenticatedFinancialReportsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLandlordsRoute: AuthenticatedLandlordsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLeasesRoute: AuthenticatedLeasesRoute,
  AuthenticatedLienWaiversRoute: AuthenticatedLienWaiversRoute,
  AuthenticatedListingBannersRoute: AuthenticatedListingBannersRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedMeetingMinutesRoute: AuthenticatedMeetingMinutesRoute,
  AuthenticatedMyIdCardRoute: AuthenticatedMyIdCardRoute,
  AuthenticatedPaymentProofsRoute: AuthenticatedPaymentProofsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPreventativeMaintenanceRoute:
    AuthenticatedPreventativeMaintenanceRoute,
  AuthenticatedProgressPaymentsRoute: AuthenticatedProgressPaymentsRoute,
  AuthenticatedProjectBudgetRoute: AuthenticatedProjectBudgetRoute,
  AuthenticatedProjectDashboardRoute: AuthenticatedProjectDashboardRoute,
  AuthenticatedProjectDocumentsRoute: AuthenticatedProjectDocumentsRoute,
  AuthenticatedProjectPhotosRoute: AuthenticatedProjectPhotosRoute,
  AuthenticatedProjectSchedulesRoute: AuthenticatedProjectSchedulesRoute,
  AuthenticatedProjectTasksRoute: AuthenticatedProjectTasksRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRouteWithChildren,
  AuthenticatedProposalsRoute: AuthenticatedProposalsRoute,
  AuthenticatedPunchListRoute: AuthenticatedPunchListRoute,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedReceiptsRoute: AuthenticatedReceiptsRoute,
  AuthenticatedRecurringBillingRoute: AuthenticatedRecurringBillingRoute,
  AuthenticatedRentalIdCardsRoute: AuthenticatedRentalIdCardsRoute,
  AuthenticatedRentalMessagesRoute: AuthenticatedRentalMessagesRoute,
  AuthenticatedRentalTaxDashboardRoute: AuthenticatedRentalTaxDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedRfisRoute: AuthenticatedRfisRoute,
  AuthenticatedSafetyIncidentsRoute: AuthenticatedSafetyIncidentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSopRoute: AuthenticatedSopRoute,
  AuthenticatedSopChecklistsRoute: AuthenticatedSopChecklistsRoute,
  AuthenticatedSopFormsRoute: AuthenticatedSopFormsRoute,
  AuthenticatedSubcontractsRoute: AuthenticatedSubcontractsRoute,
  AuthenticatedSubmittalsRoute: AuthenticatedSubmittalsRoute,
  AuthenticatedSubscriptionPlansRoute: AuthenticatedSubscriptionPlansRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
  AuthenticatedTimesheetsRoute: AuthenticatedTimesheetsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CardRoute: CardRoute,
  ContactRoute: ContactRoute,
  RegisterRoute: RegisterRoute,
  RentRoute: RentRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
