/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedSuppliersRouteImport } from './routes/_authenticated/suppliers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedRentalTaxDashboardRouteImport } from './routes/_authenticated/rental-tax-dashboard'
import { Route as AuthenticatedRentalMessagesRouteImport } from './routes/_authenticated/rental-messages'
import { Route as AuthenticatedRentalIdCardsRouteImport } from './routes/_authenticated/rental-id-cards'
import { Route as AuthenticatedRecurringBillingRouteImport } from './routes/_authenticated/recurring-billing'
import { Route as AuthenticatedPurchaseOrdersRouteImport } from './routes/_authenticated/purchase-orders'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPreventativeMaintenanceRouteImport } from './routes/_authenticated/preventative-maintenance'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPaymentProofsRouteImport } from './routes/_authenticated/payment-proofs'
import { Route as AuthenticatedMaintenanceRouteImport } from './routes/_authenticated/maintenance'
import { Route as AuthenticatedListingBannersRouteImport } from './routes/_authenticated/listing-banners'
import { Route as AuthenticatedLeasesRouteImport } from './routes/_authenticated/leases'
import { Route as AuthenticatedInventoryRouteImport } from './routes/_authenticated/inventory'
import { Route as AuthenticatedFinancialReportsRouteImport } from './routes/_authenticated/financial-reports'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedEquipmentRentalsRouteImport } from './routes/_authenticated/equipment-rentals'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedELeasingRouteImport } from './routes/_authenticated/e-leasing'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedPropertiesIdRouteImport } from './routes/_authenticated/properties.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersRoute = AuthenticatedSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRentalTaxDashboardRoute =
  AuthenticatedRentalTaxDashboardRouteImport.update({
    id: '/rental-tax-dashboard',
    path: '/rental-tax-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRentalMessagesRoute =
  AuthenticatedRentalMessagesRouteImport.update({
    id: '/rental-messages',
    path: '/rental-messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRentalIdCardsRoute =
  AuthenticatedRentalIdCardsRouteImport.update({
    id: '/rental-id-cards',
    path: '/rental-id-cards',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRecurringBillingRoute =
  AuthenticatedRecurringBillingRouteImport.update({
    id: '/recurring-billing',
    path: '/recurring-billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchaseOrdersRoute =
  AuthenticatedPurchaseOrdersRouteImport.update({
    id: '/purchase-orders',
    path: '/purchase-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPreventativeMaintenanceRoute =
  AuthenticatedPreventativeMaintenanceRouteImport.update({
    id: '/preventative-maintenance',
    path: '/preventative-maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentProofsRoute =
  AuthenticatedPaymentProofsRouteImport.update({
    id: '/payment-proofs',
    path: '/payment-proofs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceRoute =
  AuthenticatedMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedListingBannersRoute =
  AuthenticatedListingBannersRouteImport.update({
    id: '/listing-banners',
    path: '/listing-banners',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeasesRoute = AuthenticatedLeasesRouteImport.update({
  id: '/leases',
  path: '/leases',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryRoute = AuthenticatedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinancialReportsRoute =
  AuthenticatedFinancialReportsRouteImport.update({
    id: '/financial-reports',
    path: '/financial-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRentalsRoute =
  AuthenticatedEquipmentRentalsRouteImport.update({
    id: '/equipment-rentals',
    path: '/equipment-rentals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedELeasingRoute = AuthenticatedELeasingRouteImport.update({
  id: '/e-leasing',
  path: '/e-leasing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPropertiesIdRoute =
  AuthenticatedPropertiesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPropertiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/e-leasing': typeof AuthenticatedELeasingRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/listing-banners': typeof AuthenticatedListingBannersRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/e-leasing': typeof AuthenticatedELeasingRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/inventory': typeof AuthenticatedInventoryRoute
  '/leases': typeof AuthenticatedLeasesRoute
  '/listing-banners': typeof AuthenticatedListingBannersRoute
  '/maintenance': typeof AuthenticatedMaintenanceRoute
  '/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/suppliers': typeof AuthenticatedSuppliersRoute
  '/tenants': typeof AuthenticatedTenantsRoute
  '/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/e-leasing': typeof AuthenticatedELeasingRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/equipment-rentals': typeof AuthenticatedEquipmentRentalsRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/financial-reports': typeof AuthenticatedFinancialReportsRoute
  '/_authenticated/inventory': typeof AuthenticatedInventoryRoute
  '/_authenticated/leases': typeof AuthenticatedLeasesRoute
  '/_authenticated/listing-banners': typeof AuthenticatedListingBannersRoute
  '/_authenticated/maintenance': typeof AuthenticatedMaintenanceRoute
  '/_authenticated/payment-proofs': typeof AuthenticatedPaymentProofsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/preventative-maintenance': typeof AuthenticatedPreventativeMaintenanceRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRouteWithChildren
  '/_authenticated/purchase-orders': typeof AuthenticatedPurchaseOrdersRoute
  '/_authenticated/recurring-billing': typeof AuthenticatedRecurringBillingRoute
  '/_authenticated/rental-id-cards': typeof AuthenticatedRentalIdCardsRoute
  '/_authenticated/rental-messages': typeof AuthenticatedRentalMessagesRoute
  '/_authenticated/rental-tax-dashboard': typeof AuthenticatedRentalTaxDashboardRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/suppliers': typeof AuthenticatedSuppliersRoute
  '/_authenticated/tenants': typeof AuthenticatedTenantsRoute
  '/_authenticated/properties/$id': typeof AuthenticatedPropertiesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/assets'
    | '/dashboard'
    | '/e-leasing'
    | '/employees'
    | '/equipment-rentals'
    | '/expenses'
    | '/financial-reports'
    | '/inventory'
    | '/leases'
    | '/listing-banners'
    | '/maintenance'
    | '/payment-proofs'
    | '/payments'
    | '/preventative-maintenance'
    | '/projects'
    | '/properties'
    | '/purchase-orders'
    | '/recurring-billing'
    | '/rental-id-cards'
    | '/rental-messages'
    | '/rental-tax-dashboard'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/tenants'
    | '/properties/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/assets'
    | '/dashboard'
    | '/e-leasing'
    | '/employees'
    | '/equipment-rentals'
    | '/expenses'
    | '/financial-reports'
    | '/inventory'
    | '/leases'
    | '/listing-banners'
    | '/maintenance'
    | '/payment-proofs'
    | '/payments'
    | '/preventative-maintenance'
    | '/projects'
    | '/properties'
    | '/purchase-orders'
    | '/recurring-billing'
    | '/rental-id-cards'
    | '/rental-messages'
    | '/rental-tax-dashboard'
    | '/reports'
    | '/settings'
    | '/suppliers'
    | '/tenants'
    | '/properties/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/_authenticated/assets'
    | '/_authenticated/dashboard'
    | '/_authenticated/e-leasing'
    | '/_authenticated/employees'
    | '/_authenticated/equipment-rentals'
    | '/_authenticated/expenses'
    | '/_authenticated/financial-reports'
    | '/_authenticated/inventory'
    | '/_authenticated/leases'
    | '/_authenticated/listing-banners'
    | '/_authenticated/maintenance'
    | '/_authenticated/payment-proofs'
    | '/_authenticated/payments'
    | '/_authenticated/preventative-maintenance'
    | '/_authenticated/projects'
    | '/_authenticated/properties'
    | '/_authenticated/purchase-orders'
    | '/_authenticated/recurring-billing'
    | '/_authenticated/rental-id-cards'
    | '/_authenticated/rental-messages'
    | '/_authenticated/rental-tax-dashboard'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/suppliers'
    | '/_authenticated/tenants'
    | '/_authenticated/properties/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers': {
      id: '/_authenticated/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-tax-dashboard': {
      id: '/_authenticated/rental-tax-dashboard'
      path: '/rental-tax-dashboard'
      fullPath: '/rental-tax-dashboard'
      preLoaderRoute: typeof AuthenticatedRentalTaxDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-messages': {
      id: '/_authenticated/rental-messages'
      path: '/rental-messages'
      fullPath: '/rental-messages'
      preLoaderRoute: typeof AuthenticatedRentalMessagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rental-id-cards': {
      id: '/_authenticated/rental-id-cards'
      path: '/rental-id-cards'
      fullPath: '/rental-id-cards'
      preLoaderRoute: typeof AuthenticatedRentalIdCardsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring-billing': {
      id: '/_authenticated/recurring-billing'
      path: '/recurring-billing'
      fullPath: '/recurring-billing'
      preLoaderRoute: typeof AuthenticatedRecurringBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchase-orders': {
      id: '/_authenticated/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AuthenticatedPurchaseOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/preventative-maintenance': {
      id: '/_authenticated/preventative-maintenance'
      path: '/preventative-maintenance'
      fullPath: '/preventative-maintenance'
      preLoaderRoute: typeof AuthenticatedPreventativeMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-proofs': {
      id: '/_authenticated/payment-proofs'
      path: '/payment-proofs'
      fullPath: '/payment-proofs'
      preLoaderRoute: typeof AuthenticatedPaymentProofsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance': {
      id: '/_authenticated/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/listing-banners': {
      id: '/_authenticated/listing-banners'
      path: '/listing-banners'
      fullPath: '/listing-banners'
      preLoaderRoute: typeof AuthenticatedListingBannersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leases': {
      id: '/_authenticated/leases'
      path: '/leases'
      fullPath: '/leases'
      preLoaderRoute: typeof AuthenticatedLeasesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory': {
      id: '/_authenticated/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthenticatedInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-reports': {
      id: '/_authenticated/financial-reports'
      path: '/financial-reports'
      fullPath: '/financial-reports'
      preLoaderRoute: typeof AuthenticatedFinancialReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment-rentals': {
      id: '/_authenticated/equipment-rentals'
      path: '/equipment-rentals'
      fullPath: '/equipment-rentals'
      preLoaderRoute: typeof AuthenticatedEquipmentRentalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/e-leasing': {
      id: '/_authenticated/e-leasing'
      path: '/e-leasing'
      fullPath: '/e-leasing'
      preLoaderRoute: typeof AuthenticatedELeasingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/properties/$id': {
      id: '/_authenticated/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof AuthenticatedPropertiesIdRouteImport
      parentRoute: typeof AuthenticatedPropertiesRoute
    }
  }
}

interface AuthenticatedPropertiesRouteChildren {
  AuthenticatedPropertiesIdRoute: typeof AuthenticatedPropertiesIdRoute
}

const AuthenticatedPropertiesRouteChildren: AuthenticatedPropertiesRouteChildren =
  {
    AuthenticatedPropertiesIdRoute: AuthenticatedPropertiesIdRoute,
  }

const AuthenticatedPropertiesRouteWithChildren =
  AuthenticatedPropertiesRoute._addFileChildren(
    AuthenticatedPropertiesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedELeasingRoute: typeof AuthenticatedELeasingRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedEquipmentRentalsRoute: typeof AuthenticatedEquipmentRentalsRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFinancialReportsRoute: typeof AuthenticatedFinancialReportsRoute
  AuthenticatedInventoryRoute: typeof AuthenticatedInventoryRoute
  AuthenticatedLeasesRoute: typeof AuthenticatedLeasesRoute
  AuthenticatedListingBannersRoute: typeof AuthenticatedListingBannersRoute
  AuthenticatedMaintenanceRoute: typeof AuthenticatedMaintenanceRoute
  AuthenticatedPaymentProofsRoute: typeof AuthenticatedPaymentProofsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPreventativeMaintenanceRoute: typeof AuthenticatedPreventativeMaintenanceRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRouteWithChildren
  AuthenticatedPurchaseOrdersRoute: typeof AuthenticatedPurchaseOrdersRoute
  AuthenticatedRecurringBillingRoute: typeof AuthenticatedRecurringBillingRoute
  AuthenticatedRentalIdCardsRoute: typeof AuthenticatedRentalIdCardsRoute
  AuthenticatedRentalMessagesRoute: typeof AuthenticatedRentalMessagesRoute
  AuthenticatedRentalTaxDashboardRoute: typeof AuthenticatedRentalTaxDashboardRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuppliersRoute: typeof AuthenticatedSuppliersRoute
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedELeasingRoute: AuthenticatedELeasingRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedEquipmentRentalsRoute: AuthenticatedEquipmentRentalsRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFinancialReportsRoute: AuthenticatedFinancialReportsRoute,
  AuthenticatedInventoryRoute: AuthenticatedInventoryRoute,
  AuthenticatedLeasesRoute: AuthenticatedLeasesRoute,
  AuthenticatedListingBannersRoute: AuthenticatedListingBannersRoute,
  AuthenticatedMaintenanceRoute: AuthenticatedMaintenanceRoute,
  AuthenticatedPaymentProofsRoute: AuthenticatedPaymentProofsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPreventativeMaintenanceRoute:
    AuthenticatedPreventativeMaintenanceRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRouteWithChildren,
  AuthenticatedPurchaseOrdersRoute: AuthenticatedPurchaseOrdersRoute,
  AuthenticatedRecurringBillingRoute: AuthenticatedRecurringBillingRoute,
  AuthenticatedRentalIdCardsRoute: AuthenticatedRentalIdCardsRoute,
  AuthenticatedRentalMessagesRoute: AuthenticatedRentalMessagesRoute,
  AuthenticatedRentalTaxDashboardRoute: AuthenticatedRentalTaxDashboardRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuppliersRoute: AuthenticatedSuppliersRoute,
  AuthenticatedTenantsRoute: AuthenticatedTenantsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
